### ISSUE TITLE
document._currentScript not needed

### ISSUE THREAD

**Issue by warpech** [Starcounter/Guidelines#32] opened 2017-06-20 20:10 UTC
Many of our sample and prefab apps (and few pages in Docs) have a variant of the following line:

```js
var script = document._currentScript || document.currentScript;
var template = script.previousElementSibling;
```

`document._currentScript` was only needed in IE11, but we don't support that browser anymore. 

Therefore, in all of our codes the above lines can be simplified to:

```js
var template = document.currentScript.previousElementSibling;
```

Do we have a volunteer?

**Comment by Mackiovello** [comment] 2017-06-21 03:33
I'll take care of this

**Comment by Mackiovello** [comment] 2017-06-21 05:35
`_currentScript` is no longer used in the sample apps, I went over these: https://github.com/search?p=1&q=org%3AStarcounterApps+document._currentScript&type=Code

Did not touch the juicy-elements. Do we have the same browser support for them? 

It was also used once in the Docs

Closing as done.

**Comment by warpech** [comment] 2017-06-21 07:27
Wow, thanks so much!

There are also few apps in the "Starcounter" org. Normally I use advanced search at https://docs.starcounter.io/search/ to search in all our orgs.

Regarding Juicy and Palindrom components that's another story, I will just create issues there.

**Comment by Mackiovello** [comment] 2017-06-21 07:50
Fixed it in the last apps. Did not touch SyncEngine, asked @miyconst about it.

**Comment by miyconst** [comment] 2017-06-21 07:56
>Did not touch SyncEngine, asked @miyconst about it.

Did it.

**Comment by warpech** [comment] 2017-06-21 21:41
Thank you guys!

**Comment by habib535** [comment] 2017-06-22 09:05
Hi, This is working as expected in Chrome but seems like now Firefox and IE Edge has stopped working. Yesterday I had noticed this while trying to verify my changes on different browsers but didn't get a chance to dig into the issue and just opened a new issue for myself. https://github.com/StarcounterApps/Search/issues/10

All the event handlers are undefined and the code where we try to set/get the underlying model properties are also broken

If I revert back the old changes, they works fine.

@warpech @Mackiovello @miyconst

**Comment by Mackiovello** [comment] 2017-06-22 09:30
Reopening this issue until this is resolved.

CanIUse shows that it should work on Firefox: https://caniuse.com/#search=currentScript

**Comment by miyconst** [comment] 2017-06-22 09:33
>CanIUse shows that it should work on Firefox: https://caniuse.com/#search=currentScript

I think, it can be related to @tomalec's hack to `_currentScript` while importing templates. As far as I remember, there were some execution order issues in FF and Edge, and the script was not executed in the same context, so it was not possible to reference the template by `script.previousElementSibling`.

**Comment by warpech** [comment] 2017-06-22 11:16
Indeed, the tests are failing in KitchenSink since yesterday: https://github.com/StarcounterApps/KitchenSink/commits/develop

**Comment by warpech** [comment] 2017-06-22 11:26
> I think, it can be related to @tomalec's hack to _currentScript while importing templates.

I've searched https://github.com/Juicy/juicy-html and https://github.com/Juicy/imported-template and cannot find any explicit hack. @tomalec do you know the reason for this problem?

**Comment by tomalec** [comment] 2017-06-22 11:30
Well, here comes the hack: https://github.com/Juicy/imported-template/blob/master/imported-template.html#L17-L32

Would have to investigate deeper to check what's happening. Do we have the issue isolated somehow? Is the Search app only one failing? How urgent is that?

**Comment by warpech** [comment] 2017-06-22 11:51
When you scroll up this issue, you will see dozens of linked commits. Each of these commits broke Firefox and Edge in a view where it was made.

So I can say it is severe, but speaking of urgency, I think that unfortunately it is more urgent to **revert** these commits. Otherwise, whatever solution you can propose, will anyway work only starting from Starcounter 2.3.1.x.

@tomalec can you pls make an issue about investigating this in `imported-template` after migration to CE v1, P 2.0?

Sorry @Mackiovello. We should have gone the sacred PR way.

**Comment by Mackiovello** [comment] 2017-06-22 12:02
> Sorry @Mackiovello. We should have gone the sacred PR way.

😞 

> it is more urgent to revert these commits.

My bad, I'll fix it right away

**Comment by Mackiovello** [comment] 2017-06-22 12:19
We're back to square one

**Comment by tomalec** [comment] 2017-06-23 09:59
> When you scroll up this issue, you will see dozens of linked commits. Each of these commits broke Firefox and Edge in a view where it was made.

@warpech,. @habib535 
I'm not asking about "commits" but about "broke ". So, not the code that introduced the problem, but how can I see what is the problem and what is minimum set of steps I have to take to see failing Firefox? 

Is it just:
 1. Install latest Starcounter,
 2. Clone Search app from develop
 3. open localhost:8080/search 
 4. See an error in console
?

**Comment by tomalec** [comment] 2017-06-23 10:09
I have checked with SC 2.3.1.6523
1. Clone KitchenSink@29dc2f67e19347ac7674e45f9cf3f5567c8e7fbc (before reverting)
2. open http://localhost:8080/KitchenSink/ProgressBar
3. click "DOWNLOAD.."

Everything work as expected console is clean.
See an error in console

**Comment by tomalec** [comment] 2017-06-23 10:31
Ok, so here is the answer why it is broken in FF and Edge: https://github.com/webcomponents/webcomponentsjs/blob/v0/src/HTMLImports/base.js#L58-L59

It's because of the way HTML Imports polyfill works - it assigns only `_currentScript`. I don't think I should make an issue in `imported-template` as this is general polyfill issue. I would keep this issue open to investigate it after WebComponents v1 it seems it's fixed there https://github.com/webcomponents/html-imports/blob/439987cc203ac84e4bffd36278f0b933cd7b8cda/src/html-imports.js#L16-L30
Especially, that in new HTML Imports polyfill, this is no longer external document, so more-or-less there is nothing to polyfill around scripts execution.

**Comment by tomalec** [comment] 2017-06-23 10:35
@Mackiovello maybe we could also add a note somewhere, to clarify such doubts, that this is needed due to HTML Imports polyfill

**Comment by warpech** [comment] 2018-02-07 08:53
Clarification: `document._currentScript` is not needed for views that use Web Components V1 and Polymer 2.

It is still needed for views that use Web Components V0 and Polymer 1.

**Comment by tomalec** [comment] 2018-02-20 10:55
Given the elements and docs are updated, I think we can close this issue. If `_currentScript` is used in any app, it should be considered as a cleanup issue there.

**Closed by tomalec** 2018-02-20 10:55 UTC
Labels: web
